### ISSUE TITLE
doesnt fucking work

### ISSUE THREAD

**Issue by cyon-coder** [n00bes/noobdumper-v2#1]
https://i.imgur.com/xtHS5tQ.png

**Comment by n00bes** [comment]
use the minhook lib version according to your visual studio version https://github.com/TsudaKageyu/minhook/releases/download/v1.3.3/MinHook_133_lib.zip

**Comment by cyon-coder** [comment]
taci ba

**Comment by n00bes** [comment]
ok c&p

**Comment by rxn-ro** [comment]
> ok c&p

kys
